- .travis.yml
This PR showcases #24
I only added 14 to showcase the issue but I think it's better to add 12 as well. 15 is no LTS so it's not representative of real usage.
> Tests pass with unhandled rejections

- cjs/html/select-element.js
- esm/html/select-element.js
- test/html/select-element.js
Hellow,
I'm currently implementing the linkedom package in my test environment and noticed, that the `HTMLSelectElement.options` property is missing (among a few other ones). I implemented an inaccurate version of it for my own purposes, "inaccurate" since it returns a `NodeList` instance instead of the correct `HTMLOptionsCollection` (living standard) / `HTMLCollection`. Furthermore, I included a test as well and at least on Ubuntu@WSL it writes a bunch of green 100's.
Thanks for your work, really appreciate it.
Sincerely,
Sam.
> [TASK] Add options property on HTMLSelectElement

- cjs/shared/parse-from-string.js
- esm/shared/parse-from-string.js
Both nodes and attributes can skip a lot of checks while being appended from a fresh HTML parse.
The gain doesn't seem to be too relevant though, but there's surely less moving parts and it looks simpler this way.
> Fast append on parsing

- cjs/interface/element.js
- esm/interface/element.js
- test/interface/element.js
The new implementation should properly handle things like:
```
el.outerHTML = 'hello';
el.outerHTML = '<p>hello</p> world'
```
The current implementation will throw an exception for the first case and will set it to `'<p>hello</p>' ` instead of `'<p>hello</p> world'` in the 2nd case.`
> Fix set outerHTML()

- cjs/interface/comment.js
- cjs/interface/element.js
- cjs/interface/text.js
- cjs/shared/text-escaper.js
- esm/interface/comment.js
- esm/interface/element.js
- esm/interface/text.js
- esm/shared/text-escaper.js
- package.json
- test/html/element.js
- test/html/script-element.js
- test/shared/text-escaper.js
- types/shared/text-escaper.d.ts
This MR does the following:
* it keeps parsing of entities decoded
* it escapes only `<`, `>`, and `&` in text and comments, plus `160` char as `&nbsp;`
This MR should close https://github.com/WebReflection/linkedom/pull/64 too.
> Fix #62 - Follow specs for CharsetData un/escape

- test/assert.js
- test/html/anchor-element.js
- test/index.js
This MR makes it possible to run, as example:
```sh
npm run cjs && node test/html/anchor-element.js
```
So that one doesn't need to test the world when creating a new element or implementing a new feature.
> Fix #67 - Moved global symbol into assert file

- cjs/interface/element.js
- cjs/interface/node.js
- cjs/mixin/parent-node.js
- esm/interface/element.js
- esm/interface/node.js
- esm/mixin/parent-node.js
- types/interface/document.d.ts
- types/interface/element.d.ts
- types/interface/image.d.ts
- types/interface/node.d.ts
- types/mixin/parent-node.d.ts
- worker.js
When using linkedom in a Typescript project, some functionality causes Typescript errors, despite that functionality working.  [Here's one example](https://github.com/WebReflection/linkedom/issues/99), another comes from accessing `innerText` on an element returned from a `querySelector`
This PR updates type definitions for the methods  `insertBefore`, `appendChild`, `replaceChild`,`removeChild` on `Node`. 
These updated to more closely match the functionality they provide, but still cause errors from the typescript compiler as they don't exactly match those provided by `globalThis.Node`.  After this change, the errors reported when implementing linkedom in another project go away.
This also updates the `NodeStruct` type to extend the `Element` type.  This enables accessing element …
> Type definition updates

- cjs/interface/css-style-declaration.js
- esm/interface/css-style-declaration.js
- test/interface/css-style-declaration.js
- types/esm/interface/css-style-declaration.d.ts
- worker.js
Add support for `CSSStyleDeclaration` property get, set, and remove:
- [`CSSStyleDeclaration.getPropertyValue()`](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/getPropertyValue)
- [`CSSStyleDeclaration.setProperty()`](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/setProperty)
-  [`CSSStyleDeclaration.removeProperty()`](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/removeProperty)
Fix https://github.com/WebReflection/linkedom/issues/113
> Fix #113 - Add support for `CSSStyleDeclaration` property get, set, and remove

- cjs/interface/custom-element-registry.js
- cjs/interface/element.js
- cjs/interface/shadow-root.js
- cjs/shared/node.js
- cjs/shared/shadow-roots.js
- esm/interface/custom-element-registry.js
- esm/interface/element.js
- esm/interface/shadow-root.js
- esm/shared/node.js
- esm/shared/shadow-roots.js
- test/interface/custom-element-registry.js
- test/interface/shadow-root.js
- types/esm/interface/shadow-root.d.ts
- types/esm/shared/shadow-roots.d.ts
- worker.js
Thanks for this wonderful library!  This PR makes sure to fire `connectedCallback` and `disconnectedCallback` even for custom elements contained within shadow roots of other custom elements.  
When recursively firing `connectedCallback` and `disconnectedCallback` we need to traverse down through any shadow roots we find along the way.
And then when determining `isConnected` for a node within a shadow root, we need to traverse up through shadow root host elements to find our way to the owner document.  In order to facilitate this, we implement the [`host`](https://dom.spec.whatwg.org/#dom-shadowroot-host) property for shadow roots.
> support shadow root nested custom elements

- package.json
Add "types" field to "exports" object in package.json in order to make types available to projects using TypeScript and ESM (NodeNext module resolution).
> Add "types" field to "exports"

- esm/interface/element.js
- test/interface/clone-node.js
This fixes missing ownerElement when attribute is cloned. See included example.
```js
import { parseHTML } from './esm/index.js';
const w = parseHTML(`<html><body>
<select value="{{fruit=$value}}" each="{{[fruits,'f']}}"><option value="{{f}}">{{f}}</option></select>
</body></html>`);
// w.document.toString();
// console.log(w.document.body.innerHTML);
const notClone = w.document.body.firstElementChild.firstElementChild;
const notCloneAt = notClone.attributes[0];
console.log(notCloneAt.name, notCloneAt.value, notCloneAt.ownerElement.outerHTML);
const clone = w.document.body.firstElementChild.firstElementChild.cloneNode(true);
const cloneAt = clone.attributes[0];
console.log(cloneAt.name, cloneAt.value, cloneAt.ownerElement.outerHTML); // without a fix ownerElement is not assigned
```
> fix attribute clone missing ownerElement

- cjs/html/i-frame-element.js
- esm/html/i-frame-element.js
- test/html/i-frame-element.js
- types/commonjs/canvas-shim.d.cts
- types/esm/html/i-frame-element.d.ts
- worker.js
Added following `iframe` attributes:
- [srcdoc](https://html.spec.whatwg.org/multipage/iframe-embed-object.html#attr-iframe-srcdoc) — A document to render in the iframe
- [name](https://html.spec.whatwg.org/multipage/iframe-embed-object.html#attr-iframe-name) — Name of nested navigable
- [allow](https://html.spec.whatwg.org/multipage/iframe-embed-object.html#attr-iframe-allow) — Permissions policy to be applied to the iframe's contents
- [allowFullscreen](https://html.spec.whatwg.org/multipage/iframe-embed-object.html#attr-iframe-allowfullscreen) — Whether to allow the iframe's contents to use `requestFullscreen()`
- [referrerPolicy](https://html.spec.whatwg.org/multipage/iframe-embed-object.html#attr-iframe-referrerpolicy) — Referrer policy for fetches initiated by the element
- …
> Added `iframe` attributes

- cjs/interface/element.js
- esm/interface/element.js
- worker.js
fix for #178: no longer adds the childNodes of the element to its shadowRoot when attaching a new shadowRoot
> fix for attachShadow no longer adding childNodes to shadowRoot

- cjs/interface/node.js
- esm/interface/node.js
- test/interface/text.js
- types/esm/interface/image.d.ts
- types/esm/interface/node.d.ts
- types/esm/shared/node.d.ts
- worker.js
the `<html>` element is [HTMLHtmlElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLHtmlElement)
`getRootNode()` returns 
An object inheriting from Node. This will differ in exact form depending on where you called getRootNode(); for example:
- Calling it on an element inside a standard web page will return an HTMLDocument object representing the entire page (or <iframe>).
- Calling it on an element inside a shadow DOM will return the associated ShadowRoot.
---
I ran in to this bug when calling getElementById on the root node but the method didn't exist with Linkedom.
Code here https://github.com/muxinc/media-chrome/blob/main/src/js/media-theme-element.js#L177-L178
> fix: getRootNode() bug

- cjs/shared/text-escaper.js
- esm/shared/text-escaper.js
- test/shared/text-escaper.js
- worker.js
Fix issue #205 
-  `&nbsp;` is the character entity reference (meant to be easily parseable by humans).
-  `&#160;` is the numeric entity reference (meant to be easily parseable by machines).
They are the same except for the fact that the latter does not need another lookup table to find its actual value, which make it compatible with XML without breaking HTML. Source off truth [offical W3C documents](https://www.w3.org/TR/html4/charset.html#h-5.3).
> Escape NBSP to xml compatible entity

- package.json
This is needed for projects using Node16/NodeNext and the `/cached` import, as otherwise it will throw an error that the import path doesn't exist
> chore: set types on /cached export too

- .gitignore
- cjs/interface/element.js
- esm/interface/element.js
- test/interface/text.js
- worker.js
Fixes https://github.com/WebReflection/linkedom/issues/223
> Fixes an issue where '0' as textContent does not work.

- types/esm/interface/node.d.ts
- types/interface/node.d.ts
`Node`'s `cloneNode()` should take the `deep` argument in type definition. Otherwise, other derived classes like `Element` also cannot take that parameter in TS.
> Add deep argument to the type of cloneNode()

- esm/html/element.js
- esm/html/slot-element.js
- esm/interface/element.js
Fixes #131
- Adds the `name` property to the slot element
- Adds `assignedNodes()` and `assignedElements()` methods
- Adds the `slot` property to the Element class
> Improve <slot> element support

- .github/workflows/node.js.yml
- cjs/html/slot-element.js
- cjs/interface/element.js
- package-lock.json
- package.json
- types/esm/html/slot-element.d.ts
- types/esm/interface/element.d.ts
- types/esm/interface/image.d.ts
- types/esm/interface/node.d.ts
- worker.js
This MR brings in a few MRs:
* https://github.com/WebReflection/linkedom/pull/230
* https://github.com/WebReflection/linkedom/pull/228
* https://github.com/WebReflection/linkedom/pull/222 which is likely gone already because it was a bad MR
* https://github.com/WebReflection/linkedom/pull/209
* https://github.com/WebReflection/linkedom/pull/204
> Release 0.16

- cjs/interface/custom-element-registry.js
- esm/interface/custom-element-registry.js
- test/interface/custom-element-registry.js
- types/esm/interface/custom-element-registry.d.ts
- types/interface/custom-element-registry.d.ts
> Implementation of `customElements.getName()`

- cjs/html/document.js
- esm/html/document.js
- test/html/document.js
- worker.js
Minimal reproducible example with linkedom 0.16.10:
```
import { parseHTML } from 'linkedom/cached';
const html = '<!DOCTYPE html><html><head><title>Test</title></head><body></body></html>';
const { document } = parseHTML(html);
console.log('Title:', document.title); // Title: Test
console.log('Title:', document.title); // Title:          <-- missing (title removed as a side-effect)
```
> Fixed: inspecting document.title deleted it as a side-effect (when cached)

- package.json
> fix: no types exports for `./worker` submodule

- esm/html/anchor-element.js
> fix: prevent losing `rel` attr on anchor element

- cjs/interface/tree-walker.js
- esm/interface/tree-walker.js
- test/interface/tree-walker.js
- worker.js
Fixes https://github.com/WebReflection/linkedom/issues/285
> Fix TreeWalker when the root element is a TextNode

- cjs/html/text-element.js
- esm/html/text-element.js
- test/html/script-element.js
- worker.js
Fix https://github.com/WebReflection/linkedom/issues/292 https://github.com/WebReflection/linkedom/issues/158 https://github.com/WebReflection/linkedom/issues/199
See also https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#specifying_a_string_as_the_replacement
> fix: unexpected special replacement pattern
